[package]
name = "sol-lang"
version = "0.0.1"
edition = "2021"
description = "Sol compiler, interpreter and overall library."
license = "MIT"
authors = ["mrpedrobraga <mrhenribraga@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.22.6"
tree-sitter-sol = "0.0.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
